services:
  - type: web
    name: fahad-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
